name: EV Radar job
on:
  schedule:
    - cron: '*/5 * * * *'  # roda a cada 5 minutos
  workflow_dispatch:

jobs:
  run-radar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run radar
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          EV_THRESHOLD: '65'
          ODD_MIN: '1.50'
        run: |
          python radar_bot.py

      - name: Upload artifact (radar csv)
        uses: actions/upload-artifact@v4
        with:
          name: radar-csv
          path: radar_ev.csv
